allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/*'
  - 'typescript-eslint'
  - vitepress@2.0.0-alpha.18
  - '@voidzero-dev/vitepress-theme@5.0.2 || 5.0.5'
  - '@types/node@26.1.2'
  - '@rolldown/binding-android-arm64@1.2.2'
  - '@rolldown/binding-darwin-arm64@1.2.2'
  - '@rolldown/binding-darwin-x64@1.2.2'
  - '@rolldown/binding-freebsd-x64@1.2.2'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.2'
  - '@rolldown/binding-linux-arm64-gnu@1.2.2'
  - '@rolldown/binding-linux-arm64-musl@1.2.2'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.2'
  - '@rolldown/binding-linux-s390x-gnu@1.2.2'
  - '@rolldown/binding-linux-x64-gnu@1.2.2'
  - '@rolldown/binding-linux-x64-musl@1.2.2'
  - '@rolldown/binding-openharmony-arm64@1.2.2'
  - '@rolldown/binding-win32-arm64-msvc@1.2.2'
  - '@rolldown/binding-win32-x64-msvc@1.2.2'
  - rolldown@1.2.2
