allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@shikijs/*'
  - shiki@4.4.3
  - '@typescript-eslint/*'
  - typescript-eslint@8.67.0 || 8.68.0 || 8.69.0
  - '@voidzero-dev/vitepress-theme@5.0.6'
  - '@types/node@26.3.0'
