allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@shikijs/*'
  - shiki@4.4.3
  - '@typescript-eslint/*'
  - typescript-eslint@8.67.0 || 8.68.0 || 8.69.0 || 8.70.0 || 8.70.1
  - '@voidzero-dev/vitepress-theme@5.0.6 || 5.0.7'
  - '@types/node@26.3.0 || 26.5.0'
  - '@iconify/vue@5.0.3'
